export const dataEn =
[
    "I feel I am a burden to others.",
    "I am unhappy to be born a man.",
    "Having fun like a child is beneath my dignity.",
    "I prefer that others decide for me.",
    "I make mistakes.",
    "I am less important than others.",
    "Deep down I long to be loved.",
    "I feel as though I am an outsider.",
    "I feel sick.",
    "Fm scared that my problems will drive me crazy.",
    "I get confused.",
    "Fm uncomfortable when others express feelings.",
    "I wish I had not been born.",
    "If I were female life would be easier.",
    "I look after others even at cost to myself.",
    "I feel a need for approval.",
    "I can't achieve what I want to.",
    "I don’t like being a leader.",
    "I don’t trust others.",
    "I feel that others don’t accept me.",
    "I rest only when I am sick.",
    "I feel that people are against me.",
    "I’m slow in learning.",
    "It is weak to be emotional.",
    "I don’t take care of myself.",
    "Expectations on me as a man are heavy.",
    "I don’t ask for what I want.",
    "I don’t like taking responsibility.",
    "I put in a lot of effort and get little reward.",
    "I don't disturb others when I need help.",
    "Those whom I love go far away.",
    "My family members don’t think of me as part of them.",
    "I spend time talking about illness.",
    "I think life doesn't make sense.",
    "I feel unintelligent.",
    "I feel bad about being angry.",
    "I get into accidents or crises.",
    "I wish I was somebody else.",
    "If I take something from others, I feel obliged.",
    "I am treated as if I were a child.",
    "I find it difficult to finish what I begin.",
    "I prefer to stay silent than to speak up.",
    "I hold back from expressing love and affection.",
    "Iam different from my family members.",
    "I get worried about being ill.",
    "I fear I might go crazy.",
    "I am forgetful.",
    "I hide my feelings.",
    "Others will realize my worth only when I’m dead.",
    "As a man I feel superior.",
    "I don't like childishness in myself.",
    "I can’t do without protection from others.",
    "Even after being successful, I feel dissatisfied.",
    "I let others get their needs met first.",
    "I’m uncomfortable touching, or being touched.",
    "I prefer to observe a group rather than to take part.",
    "When new things happen I feel ill.",
    "If things get bad, I may fall apart.",
    "Thinking is a burden for me.",
    "I don't have feelings."
 ];

 export const injunctionsEn = [
    "Don't Exist",
    "Don't Be You",
    "Don't Be A Child",
    "Don't Grow Up",
    "Don't Succeed",
    "Don't Be Important",
    "Don't Be Close",
    "Don't Belong",
    "Don't Be Well",
    "Don't Be Sane",
    "Don't Think",
    "Don't Feel"
 ];